apiVersion: dynamic-scoring.open-cluster-management.io/v1alpha1
kind: DynamicScorer
metadata:
  name: rhacm-cpu-scorer
  namespace: open-cluster-management
spec:
  description: CPU idle score from OCP built-in cluster monitoring
  configURL: <CONFIGURL_SET_BY_04_REGISTER_SCORER>
  configSyncMode: Full
  location: Internal
  scoreDestination: AddOnPlacementScore
  scoreDimensionFormat: "${node}"
  source:
    host: https://thanos-querier.openshift-monitoring.svc:9091
    path: /api/v1/query_range
    auth:
      tokenSecretRef:
        name: prometheus-token
        key: token
  scoring:
    path: /scoring
